Teams: 4
border-radius: 1415
next-change: 0
Magic-Mirror: 300
FireBallWand: 400
PortalCompass: 100
TNT-Bow: 400
TNT-Bundle: 200
Wither-Bow: 900
ForgeE: 80
ForgeO: 80
ZPlacer: 150
ZBlocker: 200
Gold-Pickaxe: 200
Revival-Totem: 1500
Poison-Shank: 300
Scaffolding: 20