Teams: 4
border-radius: 1000
next-change: 0
Magic-Mirror: 400
FireBallWand: 600
PortalCompass: 500
TNT-Bow: 400
TNT-Bundle: 200
Wither-Bow: 900
ForgeE: 100
ForgeO: 100
ZPlacer: 150
ZBlocker: 200
Gold-Pickaxe: 200
Radiance-Anchor: 1500
Ascendant-Disruptor: 1000
Poison-Shank: 300
Scaffolding: 80
Obsidian: 100
Cobblestone: 10
Iron-Block: 100
Oak-Log: 20
Curse-of-Chains: 800