name: ThroneWorlds
version: ${project.version}
main: net.stardevelopments.throneworlds.Main
api-version: 1.16
description: its pretty epic
depend: [Multiverse-Core, Multiverse-Portals]
commands:
  startgame:
    description: Starts the Throne Worlds game!
    usage: /startgame
  setteam:
    description: Allows you to choose a team!
    usage: /setteam [list|join|leave] [team]
  scatter:
    description: [DEPRECATED] Re-scatters portals
    usage: /scatter
  border:
    description: [DEPRECATED] Changes the overworld play area
    usage: /border [radius] [seconds to change]
