Teams: 4
border-radius: 1000
next-change: 0
Magic-Mirror: 300
FireBallWand: 400
PortalCompass: 100
TNT-Bow: 400
TNT-Bundle: 200
Wither-Bow: 900
ForgeE: 80
ForgeO: 80
ZPlacer: 150
ZBlocker: 200
Gold-Pickaxe: 200
Radiance-Anchor: 1500
Ascendant-Disruptor: 1500
Poison-Shank: 300
Scaffolding: 20
Obsidian: 50
Cobblestone: 10
Iron-Block: 100