name: ThroneWorlds
version: 1.0-SNAPSHOT-20.10.2020.7
main: net.stardevelopments.throneworlds.Main
api-version: 1.16
description: its pretty epic
depend: [Multiverse-Core, Multiverse-Portals]
commands:
  startgame:
    description: Starts the Throne Worlds game!
    usage: /startgame
  teams:
    description: Allows you to choose a team!
    usage: /taems [list|join|leave] [team]