name: ThroneWorlds
version: 1.0-SNAPSHOT-24.10.2020.2
main: net.stardevelopments.throneworlds.Main
api-version: 1.16
description: its pretty epic
depend: [Multiverse-Core, Multiverse-Portals]
commands:
  startgame:
    description: Starts the Throne Worlds game!
    usage: /startgame
  teams:
    description: Allows you to choose a team!
    usage: /teams [list|join|leave] [team]
  scatter:
    description: Re-scatters portals!
    usage: /scatter